### ISSUE TITLE
Authenticate all the request

### ISSUE THREAD

**Issue by mtt87** [dashy-io/dashy-server-api#17]

**Comment by framp** [comment]
Can we make a list about the requests which need to be authenticated?

users.js
- GET /users/:id NO
- GET /user YES
- DEL /user/:id YES (+ compare req.user.id with :id) 
- POST /users/:id/dashboards/ YES (+ compare req.user.id with :id) 
- DEL /users/:id/dashboards/:dashboardId YES (+ compare req.user.id with :id) 

dashboards.js
- POST /dashboards YES?
- GET /dashboards/:id NO?
- PUT /dashboards/:id YES? (+ compare req.user.dashboards with :id) 
- DEL /dashboards/:id YES? (+ compare req.user.dashboards with :id) 
- GET /dashboards/:id/code NO?

**Comment by mtt87** [comment]
Maybe @bettiolo can give a better answer here! :smile:

**Comment by framp** [comment]
Done (+ a frontend fix, we were deleting the board before disconnecting)

**Comment by bettiolo** [comment]
@framp can you link me the issues? It is a temporary workaround to disconnect the board before deleting it

**Comment by framp** [comment]
There is no issue to link, as I solved the problem in [8a9c383](https://github.com/dashy-io/dashy-management-console/commit/8a9c3838142bc3949f47151dce6ec26ee2e85321)

I reversed the order so that when we delete the board the current user still has the right permissions over that board.

**Comment by bettiolo** [comment]
I think that the order should be Disconnect, Delete
As in future I may want to disconnect the dashboard from may account when the dashboard is shared across the organisation.

**Comment by framp** [comment]
If you disconnect a user from a board then that user can't delete a board because it doesn't have permissions anymore.

The permission system right now is user-based and not organization-based (as organizations don't exists).

**Comment by bettiolo** [comment]
OK, this makes a lot of sense, the correct way to fix it is to ensure that when you delete a dashboard, it gets disconnected from all the users.

**Comment by framp** [comment]
Agree!

Before doing that we need to improve `mongoDataStore.js` bridge: as of now `update` forces `$set` and doesn't handle the options parameter (needed to update multiple documents)

We need to do something like this

    User.update(
      { dashboards: { $in: [ dashboardId ] } },
      { $pull: { 'dashboards': dashboardId } },
      { multi: true }
    )

**Comment by framp** [comment]
I'm still working on it

**Comment by mtt87** [comment]
You forgot to mention it at standup 🙃
