### ISSUE TITLE
Models instead of a single dataStore? Google auth in a new lib?

### ISSUE THREAD

**Issue by framp** [dashy-io/dashy-server-api#8]
Hi guys, just looking around your cool project!

What do you think about abstracting and splitting your [mongoDataStore](https://github.com/dashy-io/dashy-server-api/blob/master/lib/mongoDataStore.js) into a couple of models?

I'd personally go with a `models` directory containing `user.js` and `dashboard.js`; both files could contains simple definitions of what a user and a dashboard are.
It's usually a mongoose or a sequelize schema in my apps.

With something like that in place you could remove all the boilerplate validation code from your `controllers` in `endpoints` and replace it with a library which does the validation for you starting from the actual schemes.

One last quick tip about the login: I'd personally put all the google authentication code outside your application and in another module - I don't think it's a core mechanism of your application (and I'm pretty sure there are several other libraries which provide this very feature - check out [authom](https://github.com/jed/authom) if you feel like passport is too bloated and session-centric!)

Hoping to be useful
Cheers

**Comment by bettiolo** [comment]
Hi @framp,
what about meeting up and doing it in pair programming?
That would be excellent opportunity for me as I have never done development around mongodb!

**Comment by framp** [comment]
Sure, I'd like to :)

**Comment by bettiolo** [comment]
Regarding the auth stuff on the server, it is pretty small, only 25 lines of code, I don't think it is worth getting another dependency for that?

https://github.com/dashy-io/dashy-server-api/blob/master/endpoints/auth.js#L13-L37

Does [authom](https://github.com/jed/authom) handle the UI aspect of the authentication as well? 
That would be more interesting!

**Comment by framp** [comment]
Yeah, it's personal. It's just a matter of doing one thing well and nothing more.
As izs would put it: http://blog.izs.me/post/48281998870/unix-philosophy-and-node-js :)

It doesn't have a UI but it means less code to maintain and to test and it lets you easily add more thirdy-party authentication providers should the need arise. But mainly, it's less code to maintain.

Quite easy to implement too:

    authom.createServer({ /* google credentials */ });
    authom.createServer({ /* other service credentials */ });
    authom.on("auth", function(req, res, data) {
      User.findOneOrCreate(data.token);
    });
    authom.on("error", fn);
    app.get("/auth/:service", authom.app);

**Comment by bettiolo** [comment]
@framp do you think this one is fixed now?

**Comment by framp** [comment]
I think there is still some work needed on the model abstraction but this issue is too descriptive and can be closed
