### ISSUE TITLE
When a dashboard ls deleted it's not also deleted from the user dashboards list

### ISSUE THREAD

**Issue by mtt87** [dashy-io/dashy-server-api#9]
When you delete a dashboard  
DELETE `/dashboards/:dashboard-id`

It's only deleted but it's still associated with the user so the next time you load the user dashboards it's still in that list but you are unable to retrieve the dashboard since it's deleted.

**Comment by bettiolo** [comment]
OK, I will take a look.
Thanks mate.

**Comment by bettiolo** [comment]
Please disconnect the dashboard first using `DELETE ~/user/:user-id/dashboards/:dashboard-id` endpoint

**Comment by bettiolo** [comment]
Going to fix it properly buy disconnecting it from all the users before deleting it.

**Comment by framp** [comment]
Damn I thought we were close to releasing this
